# logging:
output_dir: ./runs
project_name: train_ddpm
exp_name: all_organ_large
logging_dir: logs
report_to: wandb
sample_every: 1000 # 1000 # sample every this many steps
sample_steps: 250 # 250 # sample inference steps
resume_from_checkpoint: latest
# model
pretrained: null # ./runs/<project_name>/<exp_name>/checkpoints/step_xxx.ckpt
# data setup
## dataset
train_data_path: /home/jiangzhongjian/projects/Data/MRI_301_processed1 # /home/Share/Data/MRI/301Hospital/FM/MRI_301_processed_all_BART/

batch_size: 4 # batch size of each GPU
resolution: 320 # resolution of input image
# precision
allow_tf32: True
mixed_precision: bf16 # choices=["no", "fp16", "bf16"]
# optimization
max_train_steps: 800000 # 400000
checkpointing_steps: 1000 # 200
checkpoints_total_limit: 10
gradient_accumulation_steps: 2
learning_rate: 1.e-4 # 2.e-5 # 1.e-4
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.05
adam_epsilon: 1.e-8
max_grad_norm: 1.0
# seed
seed: 0
# cpu num workers
num_workers: 4